=== ani07121994/eq_code/OWC_Qantas/APIntegrationApp-17-Oct/APIntegrationPrj/xsd/InvoiceData.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.InvoiceData.org"
            targetNamespace="http://www.InvoiceData.org"
            elementFormDefault="qualified">
  <xsd:element name="invoiceImport">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="header">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="documentType" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="invoiceType" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="orgID" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="invoiceNumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="invoiceDate" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="supplierId" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="supplierName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="supplierNumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="SiteID" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="SiteName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="PONumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="Taxregistrationnumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="tax" type="xsd:float" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="withholdingTax" type="xsd:float" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="invoiceTotalAmount" type="xsd:float" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="currencyCode" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="certifierName" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="employeeno" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="certifieremailAdd" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="invalidReason" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="invalidCode" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="potype" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="additionalinfo">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="docID" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="imageURL" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="Priority" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="reasontype" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="status" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="RejectionReason" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="CertifierComments" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="Alternateapprover" type="xsd:string" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="LineTotalAmount" type="xsd:float" minOccurs="0" maxOccurs="1"/>
              <xsd:element name="TaxTotalAmount" type="xsd:float" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="lineItems">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="lineItem" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="LineNo" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="lineType" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="linePONumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="POLineNumber" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="Linedescription" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="quantity" type="xsd:float"
                                minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="UOM" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="unitPrice" type="xsd:float" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="lineTotalAmount" type="xsd:float" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="taxrate" type="xsd:float" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="taxratecode" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="projectno" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="taskno" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="expenditureOrg" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="expendituredate" type="xsd:date" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="GLNo" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== ani07121994/eq_code/OWC_Jetstar/APIntegration_JS/APIntegrationPrj/public_html/AssignAmount-Source.xml
<?xml version="1.0" encoding="UTF-8" ?>
<invoiceImport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.InvoiceData.org file:/C:/JDeveloper/APIntegrationWP/APIntegrationApp/APIntegrationPrj/xsd/InvoiceData.xsd" xmlns="http://www.InvoiceData.org">
   <header>
      <documentType>documentType1</documentType>
      <invoiceType>invoiceType2</invoiceType>
      <orgID>orgID3</orgID>
      <invoiceNumber>invoiceNumber4</invoiceNumber>
      <invoiceDate>invoiceDate5</invoiceDate>
      <supplierId>supplierId6</supplierId>
      <supplierName>supplierName7</supplierName>
      <supplierNumber>supplierNumber8</supplierNumber>
      <SiteID>SiteID9</SiteID>
      <SiteName>SiteName10</SiteName>
      <PONumber>PONumber11</PONumber>
      <Taxregistrationnumber>Taxregistrationnumber12</Taxregistrationnumber>
      <tax>130.72</tax>
      <withholdingTax>140.73</withholdingTax>
      <invoiceTotalAmount>150.72</invoiceTotalAmount>
      <currencyCode>currencyCode16</currencyCode>
      <certifierName>certifierName17</certifierName>
      <employeeno>employeeno18</employeeno>
      <certifieremailAdd>certifieremailAdd19</certifieremailAdd>
      <invalidReason>invalidReason20</invalidReason>
      <invalidCode>invalidCode21</invalidCode>
      <potype>potype22</potype>
   </header>
   <additionalinfo>
      <docID>docID23</docID>
      <imageURL>imageURL24</imageURL>
      <Priority>Priority25</Priority>
      <reasontype>reasontype26</reasontype>
      <status>status27</status>
      <RejectionReason>RejectionReason28</RejectionReason>
      <CertifierComments>CertifierComments29</CertifierComments>
      <Alternateapprover>Alternateapprover30</Alternateapprover>
      <LineTotalAmount>310.73</LineTotalAmount>
      <TaxTotalAmount>320.72</TaxTotalAmount>
   </additionalinfo>
   <lineItems>
      <lineItem>
         <LineNo>33</LineNo>
         <lineType>lineType34</lineType>
         <linePONumber>linePONumber35</linePONumber>
         <POLineNumber>POLineNumber36</POLineNumber>
         <Linedescription>Linedescription37</Linedescription>
         <quantity>380.72</quantity>
         <UOM>UOM39</UOM>
         <unitPrice>400.72</unitPrice>
         <lineTotalAmount>410.72</lineTotalAmount>
         <taxrate>420.72</taxrate>
         <taxratecode>taxratecode43</taxratecode>
         <projectno>projectno44</projectno>
         <taskno>taskno45</taskno>
         <expenditureOrg>expenditureOrg46</expenditureOrg>
         <expendituredate>2016-03-29</expendituredate>
         <GLNo>GLNo47</GLNo>
      </lineItem>
      <lineItem>
         <LineNo>48</LineNo>
         <lineType>lineType49</lineType>
         <linePONumber>linePONumber50</linePONumber>
         <POLineNumber>POLineNumber51</POLineNumber>
         <Linedescription>Linedescription52</Linedescription>
         <quantity>530.72</quantity>
         <UOM>UOM54</UOM>
         <unitPrice>550.72</unitPrice>
         <lineTotalAmount>560.72</lineTotalAmount>
         <taxrate>570.72</taxrate>
         <taxratecode>taxratecode58</taxratecode>
         <projectno>projectno59</projectno>
         <taskno>taskno60</taskno>
         <expenditureOrg>expenditureOrg61</expenditureOrg>
         <expendituredate>2016-03-29</expendituredate>
         <GLNo>GLNo62</GLNo>
      </lineItem>
      <lineItem>
         <LineNo>63</LineNo>
         <lineType>lineType64</lineType>
         <linePONumber>linePONumber65</linePONumber>
         <POLineNumber>POLineNumber66</POLineNumber>
         <Linedescription>Linedescription67</Linedescription>
         <quantity>680.72</quantity>
         <UOM>UOM69</UOM>
         <unitPrice>700.72</unitPrice>
         <lineTotalAmount>710.72</lineTotalAmount>
         <taxrate>720.72</taxrate>
         <taxratecode>taxratecode73</taxratecode>
         <projectno>projectno74</projectno>
         <taskno>taskno75</taskno>
         <expenditureOrg>expenditureOrg76</expenditureOrg>
         <expendituredate>2016-03-29</expendituredate>
         <GLNo>GLNo77</GLNo>
      </lineItem>
   </lineItems>
</invoiceImport>
